
server:
  port: 8765
---


spring:
  datasource:
    username: root
    password: lj20001112
    url: jdbc:mysql://49.235.245.111:3306/boyue?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


---
#mybaits≈‰÷√
mybatis:
  type-aliases-package: Boye_api.mybatis
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true



#∑÷“≥
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

---
#minio
upload:
  endpoint: http://106.15.193.103:9000/
  accessKey: minioadmin
  secretKey: minioadmin



